fifth/basic/urls.py
from django.urls import path
from basic import views

app_name = "basic"

urlpatterns = [

  path("other/",views.other,name='other'),
  path("relative/",views.relative,name='relative')
]

fifth/fifth/urls.py
from django.contrib import admin
from django.urls import path,include
from basic import views

urlpatterns = [
    path("",views.index, name="index"),
    path("basic/",include('basic.urls')),
    path('admin/', admin.site.urls),
]

fifth/basic/models.py
from django.db import models

# Create your models here.

fifth/basic/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    mydict={'text':'Hello world!', 'number':100}
    return render(request,'basic/index.html', context=mydict)

def other(request):
    return render(request,'basic/other.html')

def relative(request):
    return render(request,'basic/relative_url.html')

fifth/templates/basic/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
   </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <div class='container'>
  <!-- Links -->
      <a class='navbar-brand' href="{% url 'index' %}">INDEX</a>
<ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'basic:other' %}">Other</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'basic:relative' %}">Relative</a>
    </li>
</ul>


  </div>
</nav>
 <div class="container">
   {% block body_block %}
   {% endblock %}

 </div>
  </body>
</html>

fifth/templates/basic/index.html
<!DOCTYPE html>
{% extends "basic/base.html "%}
{% block body_block %}

    <h1>WELCOME TO THE INDEX PAGE</h1>
    <h3>{{ text|cut:"Hello" }}</h3>
    <h3>{{ number }}</h3>
{% endblock %}

fifth/templates/basic/other.html
<!DOCTYPE html>

{% extends "basic/base.html "%}
{% block body_block %}

    <h1>WELCOME TO THE OTHER PAGE</h1>

{% endblock %}

fifth/templates/basic/relative_url.html
<!DOCTYPE html>

{% extends "basic/base.html "%}
{% block body_block %}

    <h1>WELCOME TO THE RELATIVE URLS PAGE</h1>

{% endblock %}